#!/bin/bash

# Define a few Colours
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color

# MAKE MAN PAGES PRETTY
#######################################################

export LESS_TERMCAP_mb=$'\E[01;31m'             # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'        # begin bold
export LESS_TERMCAP_me=$'\E[0m'                 # end mode
export LESS_TERMCAP_se=$'\E[0m'                 # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'          # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'                 # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m'       # begin underline

############################## ##################################
# ##### PROMPT SECTION ##### ####################################
############################## ##################################

# color_name='\[\033[ color_code m\]‘

rgb_restore='\[\033[00m\]'
rgb_black='\[\033[00;30m\]'
rgb_firebrick='\[\033[00;31m\]'
rgb_red='\[\033[01;31m\]'
rgb_forest='\[\033[00;32m\]'
rgb_green='\[\033[01;32m\]'
rgb_brown='\[\033[00;33m\]'
rgb_yellow='\[\033[01;33m\]'
rgb_navy='\[\033[00;34m\]'
rgb_blue='\[\033[01;34m\]'
rgb_purple='\[\033[00;35m\]'
rgb_magenta='\[\033[01;35m\]'
rgb_cadet='\[\033[00;36m\]'
rgb_cyan='\[\033[01;36m\]'
rgb_gray='\[\033[00;37m\]'
rgb_white='\[\033[01;37m\]'

rgb_host="${rgb_cyan}"
rgb_std="{rgb_white}"

if [ `id -u` -eq 0 ]
then
 rgb_usr="${rgb_red}"
else
 rgb_usr="${rgb_green}"
fi

app_count=0
declare -a version app

hput () {
  eval hash"$1"='$2'
}

hget () {
  eval echo '${hash'"$1"'#hash}'
}

# colors

hput 'ruby'     'red'
hput 'ironruby' 'red'
hput 'node'     'green'
hput 'mono'     'yellow'
hput 'git'      'blue'
hput 'gcc'      'magenta'

# application code

function add_runtime {
  if [[ `which $1` ]] && [[ `which $1` != /usr/bin/* ]]; then
    app[app_count]=$2
    version[app_count]=$($2_version)
    let app_count=app_count+1
  fi
}

function mono_version {
  echo $(mono --version | head -1 | awk 'END { print $5 }')
}
add_runtime 'mono' 'mono'


function node_version {
  echo $(node --version)
}
add_runtime 'node' 'node'


function ironruby_version {
  echo $(ir --version | awk 'END { print $2 }')
}
add_runtime 'ir' 'ironruby'


function ruby_version {
  echo $(ruby --version | awk 'END { print $2 }')
}
add_runtime 'ruby' 'ruby'


function git_version {
  echo $(git --version | awk 'END { print $3 }')
}
add_runtime 'git' 'git'


function gcc_version {
  echo $(gcc --version | head -1 | awk 'END { print $3 }')
}
add_runtime 'gcc' 'gcc'


function vala_version {
  echo $(valac --version | awk 'END { print $2 }')
}
add_runtime 'vala' 'vala'


time="${rgb_blue}[${rgb_usr}\`date +%H\`${RGB_BLUE}:${rgb_usr}\`date +%M\`${rgb_blue}]"

hput 'yellow'  $rgb_yellow
hput 'red'     $rgb_firebrick
hput 'green'   $rgb_green
hput 'blue'    $rgb_blue
hput 'magenta' $rgb_magenta

PRE="${rgb_usr}\u${rgb_white}@${rgb_purple}\h${rgb_white}:"

i=0
while [ $i -lt $app_count ]; do
  appname=${app[$i]}
  color=`hget $appname`
  colorcode=`hget $color`
  PRE="${PRE}${colorcode}${appname}${rgb_white}-${colorcode}${version[$i]}${rgb_white}:"
  let i=i+1
done

PRE="${PRE} ${rgb_navy}\w ${rgb_usr}\\\$${rgb_restore} "

PS1="$PRE"

unset   rgb_restore   \
 rgb_black     \
 rgb_firebrick \
 rgb_host      \
 rgb_red       \
 rgb_forest    \
 rgb_green     \
 rgb_brown     \
 rgb_yellow    \
 rgb_navy      \
 rgb_blue      \
 rgb_purple    \
 rgb_magenta   \
 rgb_cadet     \
 rgb_cyan      \
 rgb_gray      \
 rgb_white     \
 rgb_std       \
 rgb_usr
