#!/bin/bash

# Define a few Colours
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color

# MAKE MAN PAGES PRETTY
#######################################################

export LESS_TERMCAP_mb=$'\E[01;31m'             # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'        # begin bold
export LESS_TERMCAP_me=$'\E[0m'                 # end mode
export LESS_TERMCAP_se=$'\E[0m'                 # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'          # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'                 # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m'       # begin underline

############################## ##################################
# ##### PROMPT SECTION ##### ####################################
############################## ##################################

# color_name='\[\033[ color_code m\]‘

rgb_restore='\[\033[00m\]'
rgb_black='\[\033[00;30m\]'
rgb_firebrick='\[\033[00;31m\]'
rgb_red='\[\033[01;31m\]'
rgb_forest='\[\033[00;32m\]'
rgb_green='\[\033[01;32m\]'
rgb_brown='\[\033[00;33m\]'
rgb_yellow='\[\033[01;33m\]'
rgb_navy='\[\033[00;34m\]'
rgb_blue='\[\033[01;34m\]'
rgb_purple='\[\033[00;35m\]'
rgb_magenta='\[\033[01;35m\]'
rgb_cadet='\[\033[00;36m\]'
rgb_cyan='\[\033[01;36m\]'
rgb_gray='\[\033[00;37m\]'
rgb_white='\[\033[01;37m\]'

rgb_host="${rgb_cyan}"
rgb_std="{rgb_white}"

if [ `id -u` -eq 0 ]
then
 rgb_usr="${rgb_red}"
else
 rgb_usr="${rgb_green}"
fi

PREFIX=$1

app_count=0
declare -a version app

hput () {
  eval hash"$1"='$2'
}

hget () {
  eval echo '${hash'"$1"'#hash}'
}

hput 'ruby'     'red'
hput 'ironruby' 'red'
hput 'node'     'green'
hput 'mono'     'yellow'
hput 'git'      'blue'


MONO_BIN=$PREFIX/bin/mono
if [ ! -z `which ${MONO_BIN}` ]; then
  MONO_PREFIX=$PREFIX
  export DYLD_LIBRARY_PATH=$MONO_PREFIX/lib:$DYLD_LIBRARY_PATH
  export LD_LIBRARY_PATH=$MONO_PREFIX/lib:$LD_LIBRARY_PATH
  export C_INCLUDE_PATH=$MONO_PREFIX/include:$GNOME_PREFIX/include
  export ACLOCAL_PATH=$MONO_PREFIX/share/aclocal
  export PKG_CONFIG_PATH=$MONO_PREFIX/lib/pkgconfig:$GNOME_PREFIX/lib/pkgconfig
  PATH=$MONO_PREFIX/bin:$PATH

  MONO_VERSION=`gmcs --version | awk 'END { print $NF }' | awk 'END { print substr($NF,0, length($NF)-2) }'`

  version[app_count]=${MONO_VERSION}
  app[app_count]='mono'
  let app_count=app_count+1
else
  if [[ `which mono` ]] && [[ `which mono` != /usr/bin/* ]]; then
    MONO_VERSION=`gmcs --version | awk 'END { print $NF }' | awk 'END { print substr($NF,0, length($NF)-2) }'`

    version[app_count]=$MONO_VERSION
    app[app_count]='mono'
    let app_count=app_count+1
  fi
fi


NODE_BIN=$PREFIX/bin/node
if [ ! -z `which ${NODE_BIN}` ]; then

  PATH=$PREFIX/bin:$PATH

  NODE_VERSION=`${NODE_BIN} --version`

  version[app_count]=$NODE_VERSION
  app[app_count]='node'
  let app_count=app_count+1

else
  if [ `which node` ] && [[ `which node` != /usr/bin/* ]]; then
    NODE_VERSION=`node --version`

    version[app_count]=$NODE_VERSION
    app[app_count]='node'
    let app_count=app_count+1
  fi
fi


IRONRUBY_BIN=$PREFIX/bin/ir
if [ ! -z `which ${IRONRUBY_BIN}` ]; then
  PATH=$PREFIX/bin:$PATH

  IRONRUBY_VERSION=`ir --version | awk 'END { print $2 }'`

  version[app_count]=$IRONRUBY_VERSION
  app[app_count]='ironruby'
  let app_count=app_count+1
else
  if [ `which ir` ] && [[ `which ir` != /usr/bin/* ]]; then
    IRONRUBY_VERSION=`ir --version | awk 'END { print $2 }'`

    version[app_count]=$IRONRUBY_VERSION
    app[app_count]='ironruby'
    let app_count=app_count+1
  fi
fi


RUBY_BIN=$PREFIX/bin/ruby
if [ ! -z `which $RUBY_BIN` ]; then
  PATH=$PREFIX/bin:$PATH

  version[app_count]=`ruby --version | awk 'END { print $2 }'`
  app[app_count]='ruby'
  let app_count=app_count+1
else
  if [ `which ruby` ] && [[ `which ruby` != /usr/bin/* ]]; then

    version[app_count]=`ruby --version | awk 'END { print $2 }'`
    app[app_count]='ruby'
    let app_count=app_count+1
  fi
fi


GIT_BIN=$PREFIX/bin/git
if [ ! -z `which $GIT_BIN` ];then
  PATH=$PREFIX/bin:$PATH
  
  version[app_count]=`git --version | awk 'END { print $3 }'`
  app[app_count]='git'
  let app_count=app_count+1
else
  if [ `which git` ] && [[ `which git` != /usr/bin/* ]]; then

    version[app_count]=`git --version | awk 'END { print $3 }'`
    app[app_count]='git'
    let app_count=app_count+1
  fi
fi


time="${rgb_blue}[${rgb_usr}\`date +%H\`${RGB_BLUE}:${rgb_usr}\`date +%M\`${rgb_blue}]"

hput 'yellow' $rgb_yellow
hput 'red'    $rgb_firebrick
hput 'green'  $rgb_green
hput 'blue'   $rgb_blue

PRE="${rgb_usr}\u${rgb_white}@${rgb_purple}\h${rgb_white}:"

i=0
while [ $i -lt $app_count ]; do
  appname=${app[$i]}
  color=`hget $appname`
  colorcode=`hget $color`
  PRE="${PRE}${colorcode}${appname}${rgb_white}-${colorcode}${version[$i]}${rgb_white}:"
  let i=i+1
done

PRE="${PRE} ${rgb_navy}\w ${rgb_usr}\\\$${rgb_restore} "

PS1="$PRE"

unset   rgb_restore   \
 rgb_black     \
 rgb_firebrick \
 rgb_host      \
 rgb_red       \
 rgb_forest    \
 rgb_green     \
 rgb_brown     \
 rgb_yellow    \
 rgb_navy      \
 rgb_blue      \
 rgb_purple    \
 rgb_magenta   \
 rgb_cadet     \
 rgb_cyan      \
 rgb_gray      \
 rgb_white     \
 rgb_std       \
 rgb_usr
