-
  name: mono
  color: yellow
  version: mono --version | head -1 | awk '{ print $5 }'
-
  name: node
  color: light_green
  version: node --version | awk '{ print substr($1, 2) }'
-
  name: ruby
  color: red
  version: ruby --version | awk '{ print $2 }'
-
  name: git
  color: blue
  version: git --version | awk '{ print $3 }'
-
  name: vala
  color: light_magenta
  version: valac --version | awk '{ print $2 }'
-
  name: gcc
  color: white
  version: gcc --version | head -1 | awk '{ print $4 }'
-
  name: clang
  color: light_black
  color256: 246
  version: clang --version | awk '{ print $3 }'
-
  name: ir
  color: light_red
  version: ir --version | awk '{ print $2 }'
-
  name: rust
  color: light_red
  version: rustc --version | awk '{ print $2 }'
-
  name: python
  color: green
  color256: 46
  version: python --version 2>&1 | head -1 | awk '{ print $2 }'
